version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      # time: '05:00' --> commented by test purposes only.
    open-pull-requests-limit: 10
